all:
	g++ -o a  L22-4F.cpp -lglut -lGL -lGLU -lm

a:
	g++ -o a  1-L21.cpp -lglut -lGL -lGLU -lm

b: 
	g++ -o a  L22-4e.cpp -lglut -lGL -lGLU -lm

d: 
	g++ -o a  exe4_a.cpp -lglut -lGL -lGLU -lm
e:
	g++ -o a  L22-2.cpp -lglut -lGL -lGLU -lm
	
